### ISSUE TITLE
Base of code

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [lessu/rs-xsd-parser#1]
Hi !
It may interesting to look here a base of code:
https://github.com/media-io/xml-schema/tree/main/xml_schema_derive/src/xsd

But I will be very happy to replace the code with this library, and only have the generation part in xml-schema ;-)

**Comment by lessu** [comment]
Thank you very much, actually my first version is based on xml-schema, that really helps me a lot.

the main problem is, I'm working on a very complex, xsd,xml-schema lakes some fields, which stop me parsing entire xsd correctly, I tried to add the missing field, but it is highly related with code generating derive, I can't only add the missing field but don't generate the code, 

And even more I doubt is there a general way to generate code for complete xsd standard.
Instead, I will only focus on my xsd.

Finally I need a lib that can represent entire xsd standard first (which is common). and for code generation part, I will only forcus on my case.
